- hosts: all
  become: true
  tasks:
  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm reset
    ignore_errors: yes

  - name: Install packages
    apt:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - ca-certificates
      - curl
      - iptables-services
    ignore_errors: yes


  - name: Install Kubernetes binaries
    apt: 
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
        - kubelet 
        - kubeadm 
        - kubectl
        - docker
    ignore_errors: yes
